# AVALIAÇÃO 11

In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import preprocessing

from src.si.data.dataset import Dataset
from src.si.io.csv import read_csv
from src.si.neuralnets.nn import NN
from src.si.neuralnets.layer import Dense, SigmoidActivation,SoftMaxActivation, ReLUActivation, LinearActivation
from src.si.linear_model.ridge_regression import RidgeRegression
from src.si.linear_model.logistic_regression import LogisticRegression
from src.si.metrics.cross_entropy import cross_entropy, cross_entropy_derivative
from src.si.metrics.accuracy import accuracy
from src.si.metrics.mse import mse, mse_derivative
from src.si.model_selection.split import train_test_split


## Exercício 12
Redes neuronais e Backpropagation

12.1) Implementa o método de backward propagation da ReLUActivation layer.
- Considera o seguinte para a propagação do erro numa layer de ativação ReLU:
• Substituir valores de erro superiores a 0 por 1
• Substituir valores de erro inferiores a 0 por 0
• Multiplicação elemento a elemento entre o erro e os valores anteriores

In [20]:
from si.neuralnets.layer import ReLUActivation

12.2) Constrói um modelo de redes neuronais adequado
ao dataset breast-bin.csv.

In [2]:
#dataset
breast_dataset = read_csv('C:/Users/Carolina/Documents/GitHub/si/datasets/breast-bin.csv', sep=',',features=True, label=True)

In [3]:
breast_dataset.X

array([[5., 1., 1., ..., 1., 1., 1.],
       [2., 1., 1., ..., 2., 1., 1.],
       [2., 1., 1., ..., 3., 1., 1.],
       ...,
       [5., 2., 2., ..., 1., 1., 2.],
       [2., 3., 2., ..., 3., 1., 1.],
       [7., 6., 6., ..., 7., 1., 1.]])

In [4]:
breast_dataset.y[:10]

array([0., 0., 0., 1., 0., 0., 0., 0., 1., 0.])

In [5]:
#standardizar o dataset
breast_dataset.X= preprocessing.StandardScaler().fit_transform(breast_dataset.X)

In [6]:
breast_train, breast_test = train_test_split(breast_dataset, test_size=0.3)

In [7]:
#dividir dataset em treino e teste
breast_train, breast_test = train_test_split(breast_dataset)

In [8]:
print(breast_train.shape())
print(breast_test.shape())

(559, 9)
(139, 9)


In [9]:
# 3 layers com sigmoid activation

l1_bin = Dense(input_size = 9, output_size=9)
l2_bin = Dense(input_size = 9, output_size=4)
l3_bin = Dense(input_size = 4, output_size=1)

l1_bin_rla = ReLUActivation()
l2_bin_rla = ReLUActivation()
l3_bin_sa = SigmoidActivation()

model_bin = NN([ l1_bin, l1_bin_rla, l2_bin, l2_bin_rla, l3_bin, l3_bin_sa], cross_entropy, cross_entropy_derivative, True)

In [10]:
model_bin.fit(dataset=breast_train)

In [19]:
model_bin.predict(breast_train)

array([[0.50000022],
       [0.49999768],
       [0.49999975],
       [0.49999971],
       [0.49999972],
       [0.49999997],
       [0.50000038],
       [0.50000031],
       [0.49999954],
       [0.4999985 ],
       [0.49999908],
       [0.50000038],
       [0.4999964 ],
       [0.49999977],
       [0.49999982],
       [0.49999905],
       [0.49999985],
       [0.50000038],
       [0.49999787],
       [0.49999725],
       [0.4999999 ],
       [0.49999987],
       [0.49999985],
       [0.49999781],
       [0.49999835],
       [0.49999942],
       [0.50000035],
       [0.50000032],
       [0.49999985],
       [0.49999854],
       [0.49999971],
       [0.50000009],
       [0.49999892],
       [0.49999975],
       [0.49999937],
       [0.49999948],
       [0.49999659],
       [0.49999947],
       [0.49999805],
       [0.49999774],
       [0.49999926],
       [0.49999737],
       [0.49999795],
       [0.49999756],
       [0.4999987 ],
       [0.49999946],
       [0.49999765],
       [0.500

12.3) Constrói um modelo de redes neuronais adequado
ao dataset cpu.csv.

In [11]:
cpu = read_csv('C:/Users/Carolina/Documents/GitHub/si/datasets/cpu.csv', sep=',',features=True, label=True)

In [12]:
cpu.y[:10]

array([ 198,  269,  220,  172,  132,  318,  367,  489,  636, 1144],
      dtype=int64)

In [13]:
cpu.X = preprocessing.StandardScaler().fit_transform(cpu.X)
cpu_train, cpu_test = train_test_split(cpu, test_size=0.3)

In [14]:
print(cpu_train.shape())
print(cpu_test.shape())

(147, 6)
(62, 6)


In [15]:
# 3 layers com ReLUActivation

l1_reg = Dense(input_size = 6, output_size=6)
l2_reg = Dense(input_size = 6, output_size=4)
l3_reg = Dense(input_size = 4, output_size=1)

l1_reg_rlua = ReLUActivation()
l2_reg_rlua = ReLUActivation()

model_reg = NN(layers=[l1_reg_rlua, l2_reg, l2_reg_rlua, l3_reg], loss_function=cross_entropy, loss_derivation=cross_entropy_derivative, verbose=True)

In [16]:
model_reg.fit(dataset=cpu_train)

In [17]:
pred = model_reg.predict(dataset=cpu_test)

In [18]:
score = mse(cpu_test.y,pred)
print(score)

2452702.267710159
