# AVALIAÇÃO 4
## Implementar o KNNRegressor com RMSE

## Exercício 5
Implementar o KNNRegressor com RMSE

5.1) Adiciona a métrica RMSE (RMQE em português) ao sub package metrics . Deves criar um módulo chamado rmse.py.

from si.metrics.rmse import rmse

5.2) Considera a estrutura da função rmse apresentada no diapositivo seguinte.
Adiciona o objeto KNNRegressor ao sub package neighbors .
Deves criar um módulo chamado knn_regressor.py para implementar este objeto.

from si.neighbors.knn_regressor import KNNRegressor

5.3) Considera a estrutura do objetoKNNRegressor apresentada no diapositivo seguinte.

5.4) Podes testar o objeto KNNRegressor num jupyter notebook usando o dataset cpu.csv (regressão)

## Testar o objeto KNNRegressor

In [1]:
import numpy as np
import matplotlib.pyplot as plt

from si.data.dataset import Dataset
from si.io.csv import read_csv
from si.model_selection.split import train_test_split
from si.metrics.accuracy import accuracy
from si.metrics.rmse import rmse
from si.neighbors.knn_regressor import KNNRegressor
from si.statistics.euclidean_distance import euclidean_distance

In [2]:
cpu = read_csv('C:/Users/Carolina/Documents/GitHub/si/datasets/cpu.csv', sep=',',features=True, label=True)

In [3]:
train_dataset, test_dataset = train_test_split(cpu)

In [4]:
print(train_dataset.X[:10])

[[   25  1310  2620   131    12    24]
 [  200  1000  4000     0     1     4]
 [  330  1000  4000     0     3     6]
 [   30  8000 64000    96    12   176]
 [  800   256  8000     0     1     4]
 [   38  8000 32000    64     8    24]
 [  133  1000  8000     9     3    12]
 [  240   512  1000     8     1     3]
 [   23 32000 64000   128    32    64]
 [   50  2000 32000    48    26    52]]


In [5]:
print(test_dataset.X[:10])

[[   25  1310  2620   131    12    24]
 [  200  1000  4000     0     1     4]
 [  330  1000  4000     0     3     6]
 [   30  8000 64000    96    12   176]
 [  800   256  8000     0     1     4]
 [   38  8000 32000    64     8    24]
 [  133  1000  8000     9     3    12]
 [  240   512  1000     8     1     3]
 [   23 32000 64000   128    32    64]
 [   50  2000 32000    48    26    52]]


In [6]:
k = 4
kmeans = KNNRegressor(k)
kmeans.fit(train_dataset)
predictions = kmeans.predict(test_dataset)
print(predictions)
print(kmeans.score(test_dataset))

[ 89.25  21.75  21.75 658.25  45.25 272.25  45.25  26.25 712.5  272.25
  67.   109.25  47.    47.    67.5   90.5   49.5   33.75 118.   109.25
  45.75  52.   109.25  21.75  25.5   47.    32.5   26.5   36.25  47.
 272.25  26.5   52.5   32.5   33.75  53.75  45.25 311.75  67.5   21.75
 272.25]
89.78241822289718


In [7]:
k = 3
kmeans = KNNRegressor(k,euclidean_distance)
kmeans.fit(train_dataset)

In [8]:
kmeans.score(test_dataset)

63.97130538983187