# AVALIAÇÃO 2
Exercício 3

## Exercício 3
Implementar o SelectPercentile

3.1) Adiciona o objeto SelectPercentile ao sub-package feature_selection. Deves criar um módulo chamado select_percentile.py para implementar este objeto
3.2) A class SelectPercentile tem uma arquitetura semelhante à classe SelectKBest. Considera a estrutura apresentada no diapositivo seguinte.
3.3) Podes testar a class SelectPercentile num jupyter notebook usando o dataset iris.csv (classificação) e o dataset cpu.csv (regressão)

In [11]:
import numpy as np
import pandas as pd

In [12]:
from src.si.io.csv import read_csv
from src.si.data.dataset import Dataset
from src.si.feature_selection.variance_threshold import VarianceThreshold
from src.si.feature_selection.select_k_best import SelectKBest
from src.si.statistics.f_classification import f_classification
from src.si.feature_selection.select_percentile import SelectPercentile

In [13]:
iris_dataset = read_csv("C:/Users/Carolina/Documents/GitHub/si/datasets/iris.csv", sep=',',features=True, label=True)

In [14]:
iris_dataset.features

['sepal_length', 'sepal_width', 'petal_length', 'petal_width']

In [15]:
iris_dataset = read_csv("C:/Users/Carolina/Documents/GitHub/si/datasets/iris.csv", sep=',',features=True, label=True)

iris_dataset.X[:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [16]:
# Variance Threshold
var_threshold = VarianceThreshold(0.5)
var_threshold.fit(iris_dataset)
transformed_dataset = var_threshold.transform(iris_dataset)
transformed_dataset.shape()

(150, 3)

In [17]:
transformed_dataset.X

array([[5.1, 1.4, 0.2],
       [4.9, 1.4, 0.2],
       [4.7, 1.3, 0.2],
       [4.6, 1.5, 0.2],
       [5. , 1.4, 0.2],
       [5.4, 1.7, 0.4],
       [4.6, 1.4, 0.3],
       [5. , 1.5, 0.2],
       [4.4, 1.4, 0.2],
       [4.9, 1.5, 0.1],
       [5.4, 1.5, 0.2],
       [4.8, 1.6, 0.2],
       [4.8, 1.4, 0.1],
       [4.3, 1.1, 0.1],
       [5.8, 1.2, 0.2],
       [5.7, 1.5, 0.4],
       [5.4, 1.3, 0.4],
       [5.1, 1.4, 0.3],
       [5.7, 1.7, 0.3],
       [5.1, 1.5, 0.3],
       [5.4, 1.7, 0.2],
       [5.1, 1.5, 0.4],
       [4.6, 1. , 0.2],
       [5.1, 1.7, 0.5],
       [4.8, 1.9, 0.2],
       [5. , 1.6, 0.2],
       [5. , 1.6, 0.4],
       [5.2, 1.5, 0.2],
       [5.2, 1.4, 0.2],
       [4.7, 1.6, 0.2],
       [4.8, 1.6, 0.2],
       [5.4, 1.5, 0.4],
       [5.2, 1.5, 0.1],
       [5.5, 1.4, 0.2],
       [4.9, 1.5, 0.1],
       [5. , 1.2, 0.2],
       [5.5, 1.3, 0.2],
       [4.9, 1.5, 0.1],
       [4.4, 1.3, 0.2],
       [5.1, 1.5, 0.2],
       [5. , 1.3, 0.3],
       [4.5, 1.3

In [18]:
# Select K Best with f_classification
k_best = SelectKBest(score_func=f_classification, k=2) #k=2 -> apenas 2 das melhores características
k_best.fit_transform(iris_dataset).features

['petal_width', 'petal_length']

In [19]:
k_best = SelectKBest(score_func=f_classification, k=3) #k=3 -> apenas 3 das melhores características
k_best.fit_transform(iris_dataset).features

['sepal_length', 'petal_width', 'petal_length']

In [20]:
percentile = SelectPercentile(score_func=f_classification, percentile=50)
percentile.fit_transform(iris_dataset)

print(percentile.p)
print(percentile.F)

[1.66966919e-31 1.32791652e-16 3.05197580e-91 4.37695696e-85]
[ 119.26450218   47.3644614  1179.0343277   959.32440573]
