# AVALIAÇÃO 1
Exercício 1 e 2

## Exercício 1
NumPy array Indexing/Slicing

1.1) Neste exercício, vamos usar o iris dataset.
Carrega o iris.csv usando o método read apropriado para o tipo de ficheiro.

In [1]:
import numpy as np
from src.si.io.csv import read_csv
iris_dataset = read_csv("C:/Users/Carolina/Documents/GitHub/si/datasets/iris.csv", sep=',',features=True, label=True)
iris_dataset.X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [2]:
iris_dataset.summary()

sepal_length  sepal_width  petal_length  petal_width
mean        5.843333     3.054000      3.758667     1.198667
median      5.800000     3.000000      4.350000     1.300000
min         4.300000     2.000000      1.000000     0.100000
max         7.900000     4.400000      6.900000     2.500000
var         0.681122     0.186751      3.092425     0.578532

In [3]:
import pandas as pd

dataset_iris = pd.read_csv("C:/Users/Carolina/Documents/GitHub/si/datasets/iris.csv")

dataset_iris

sepal_length  sepal_width  petal_length  petal_width           class
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [4]:
dataset_iris._info_axis

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'class'], dtype='object')

In [5]:
dataset_iris.describe()

sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [6]:
dataset_iris.head(5)

sepal_length  sepal_width  petal_length  petal_width        class
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

1.2) Seleciona a primeira variável independente e verifica a dimensão do array resultante.

In [7]:
variavel_independente = iris_dataset.X[:,0]

print(variavel_independente.shape)

(150,)


In [8]:
dataset_iris.dtypes

sepal_length    float64
sepal_width     float64
petal_length    float64
petal_width     float64
class            object
dtype: object

In [9]:
prim_variavel = dataset_iris['sepal_length']
dimensao = dataset_iris['sepal_length'].shape
prim_variavel.size

150

1.3) Seleciona as últimas 5 amostras do iris dataset.
Qual a média das últimas 5 amostras para cada variável independente/feature?

In [10]:
ult_amostras = iris_dataset.X[-5:]
ult_amostras

array([[6.7, 3. , 5.2, 2.3],
       [6.3, 2.5, 5. , 1.9],
       [6.5, 3. , 5.2, 2. ],
       [6.2, 3.4, 5.4, 2.3],
       [5.9, 3. , 5.1, 1.8]])

In [11]:
ult_amostras= iris_dataset.X[-5:]
print(ult_amostras, '\n')
print('A média das últimas 5 amostras para cada variável independente/feature:')
print(ult_amostras.mean(axis=0))

[[6.7 3.  5.2 2.3]
 [6.3 2.5 5.  1.9]
 [6.5 3.  5.2 2. ]
 [6.2 3.4 5.4 2.3]
 [5.9 3.  5.1 1.8]] 

A média das últimas 5 amostras para cada variável independente/feature:
[6.32 2.98 5.18 2.06]


In [12]:
# tail() method returns the last 5 rows
ultimas5_amostras = dataset_iris.tail()
ultimas5_amostras.mean(numeric_only=True)

sepal_length    6.32
sepal_width     2.98
petal_length    5.18
petal_width     2.06
dtype: float64

1.4) Seleciona todas as amostras do dataset com valor superior ou igual a 1.
Nota que o array resultante deve ter apenas amostras com valores iguais ou superiores a 1 para todas as features.

In [13]:
amostras = iris_dataset.X[iris_dataset.X >=1]
#amostras
print(amostras.shape)

(550,)


In [14]:
amostras_iguais_superiores_um = dataset_iris.loc[(dataset_iris['sepal_length'] >= 1) & (dataset_iris['sepal_width'] >= 1) & (dataset_iris['petal_width'] >= 1) & (dataset_iris['petal_length'] >= 1)]
amostras_iguais_superiores_um

sepal_length  sepal_width  petal_length  petal_width            class
50            7.0          3.2           4.7          1.4  Iris-versicolor
51            6.4          3.2           4.5          1.5  Iris-versicolor
52            6.9          3.1           4.9          1.5  Iris-versicolor
53            5.5          2.3           4.0          1.3  Iris-versicolor
54            6.5          2.8           4.6          1.5  Iris-versicolor
..            ...          ...           ...          ...              ...
145           6.7          3.0           5.2          2.3   Iris-virginica
146           6.3          2.5           5.0          1.9   Iris-virginica
147           6.5          3.0           5.2          2.0   Iris-virginica
148           6.2          3.4           5.4          2.3   Iris-virginica
149           5.9          3.0           5.1          1.8   Iris-virginica

[100 rows x 5 columns]

1.5) Seleciona todas as amostras com a classe/label igual a ‘Irissetosa’.
Quantas amostras obténs?

In [15]:
irissetosa = iris_dataset.X[iris_dataset.y == 'Iris-setosa']

len(irissetosa)

50

In [16]:
numero_amostras = dataset_iris[dataset_iris['class'] == 'Iris-setosa']
len(numero_amostras)

50

## Exercício 2: NumPy array Indexing/Slicing

2.1) Adiciona um método ao objeto Dataset que remove todas as amostras que contêm pelo menos um valor nulo (NaN).
Nota que o objeto resultante não deve conter valores nulos em para nenhuma feature/variável independente.
Nota também que deves atualizar o vetor y removendo as entradas associadas às amostras a remover.
Deves usar apenas funções no NumPy.
Nome do método: dropna

numpy.isnan -> Teste elemento a elemento para NaN e retorne o resultado como uma matriz booleana.

numpy.any -> Teste se algum elemento da matriz ao longo de um determinado eixo é avaliado como Verdadeiro.

from si.data.dataset import Dataset -> def dropna


2.2) Adiciona um método ao objeto Dataset que substitui todas os valores nulos por outro valor (argumento da função/método).
Nota que o objeto resultante não deve conter valores nulos em para nenhuma feature/variável independente.
Deves usar apenas funções no NumPy.
Nome do método: fillna

fillna -> preenche todos os campos com dados ausentes.

nan_to_num -> Substitui NaN por zero e infinito por grandes números finitos (comportamento padrão) ou pelos números definidos pelo usuário usando as palavras-chave nan, posinf e/ou neginf .

from si.data.dataset import Dataset -> def fillna


In [38]:
#exemplo dropna()
from si.data.dataset import Dataset
x= np.array([[1, 2, 3], [1, 2, np.nan], [1,2,3],[np.nan,2,3],[1,1,3],[1,3,np.nan]])
y = np.array([1, 2, 3, 4, 5])
features = ['A', 'B', 'C']
label = 'y'
dataset = Dataset(x, y, features=features, label=label)

print('Dataset antes:\n',dataset.X)
dataset.dropna()
print('depois do dropna:\n', dataset.X)

Dataset antes:
 [[ 1.  2.  3.]
 [ 1.  2. nan]
 [ 1.  2.  3.]
 [nan  2.  3.]
 [ 1.  1.  3.]
 [ 1.  3. nan]]
depois do dropna:
 [[1. 2. 3.]
 [1. 2. 3.]
 [1. 1. 3.]]


In [39]:
#exemplo fillna()
dataset = Dataset(x, y, features=features, label=label)
dataset.fillna(50)
print(dataset.X)

[[ 1.  2.  3.]
 [ 1.  2. 50.]
 [ 1.  2.  3.]
 [50.  2.  3.]
 [ 1.  1.  3.]
 [ 1.  3. 50.]]
